open import satelliteW3
open import Plans.Semantics satelliteW3Domain
open import Plans.PlanW satelliteW3Domain
open import Data.List
open import Data.Product renaming (_,_ to _↝_)
open import Relation.Nullary.Decidable

module satelliteW3Example where

P : World
P = (satellite satellite0) ∷ (instrument instrument0) ∷ (supports instrument0 spectrograph4) ∷ (calibration_target instrument0 star0) ∷ (on_board instrument0 satellite0) ∷ (power_avail satellite0) ∷ (pointing satellite0 star8) ∷ (satellite satellite1) ∷ (instrument instrument1) ∷ (supports instrument1 infrared0) ∷ (supports instrument1 infrared1) ∷ (calibration_target instrument1 groundstation3) ∷ (instrument instrument2) ∷ (supports instrument2 infrared1) ∷ (supports instrument2 infrared0) ∷ (calibration_target instrument2 star2) ∷ (instrument instrument3) ∷ (supports instrument3 spectrograph4) ∷ (supports instrument3 infrared1) ∷ (supports instrument3 thermograph2) ∷ (calibration_target instrument3 star0) ∷ (on_board instrument1 satellite1) ∷ (on_board instrument2 satellite1) ∷ (on_board instrument3 satellite1) ∷ (power_avail satellite1) ∷ (pointing satellite1 groundstation3) ∷ (satellite satellite2) ∷ (instrument instrument4) ∷ (supports instrument4 infrared1) ∷ (supports instrument4 image3) ∷ (supports instrument4 infrared0) ∷ (calibration_target instrument4 star2) ∷ (instrument instrument5) ∷ (supports instrument5 thermograph2) ∷ (supports instrument5 spectrograph4) ∷ (calibration_target instrument5 star0) ∷ (instrument instrument6) ∷ (supports instrument6 infrared0) ∷ (calibration_target instrument6 groundstation3) ∷ (on_board instrument4 satellite2) ∷ (on_board instrument5 satellite2) ∷ (on_board instrument6 satellite2) ∷ (power_avail satellite2) ∷ (pointing satellite2 star4) ∷ (satellite satellite3) ∷ (instrument instrument7) ∷ (supports instrument7 image3) ∷ (calibration_target instrument7 star2) ∷ (on_board instrument7 satellite3) ∷ (power_avail satellite3) ∷ (pointing satellite3 phenomenon9) ∷ (satellite satellite4) ∷ (instrument instrument8) ∷ (supports instrument8 infrared0) ∷ (supports instrument8 spectrograph4) ∷ (supports instrument8 infrared1) ∷ (calibration_target instrument8 star2) ∷ (on_board instrument8 satellite4) ∷ (power_avail satellite4) ∷ (pointing satellite4 phenomenon9) ∷ (mode thermograph2) ∷ (mode image3) ∷ (mode infrared1) ∷ (mode spectrograph4) ∷ (mode infrared0) ∷ (direction star1) ∷ (direction star4) ∷ (direction star0) ∷ (direction groundstation3) ∷ (direction star2) ∷ (direction star5) ∷ (direction planet6) ∷ (direction phenomenon7) ∷ (direction star8) ∷ (direction phenomenon9) ∷ (direction star10) ∷ (direction star11) ∷ (direction star12) ∷ (direction planet13) ∷ (direction planet14) ∷ (direction phenomenon15) ∷ (direction planet16) ∷ (direction star17) ∷ (direction star18) ∷ (direction planet19) ∷ []

Q : State
Q = (+ ↝ (pointing satellite0 phenomenon9)) ∷ (+ ↝ (pointing satellite1 star4)) ∷ (+ ↝ (pointing satellite4 star11)) ∷ (+ ↝ (have_image star5 image3)) ∷ (+ ↝ (have_image planet6 infrared1)) ∷ (+ ↝ (have_image phenomenon7 infrared1)) ∷ (+ ↝ (have_image star8 image3)) ∷ (+ ↝ (have_image star10 thermograph2)) ∷ (+ ↝ (have_image star11 infrared1)) ∷ (+ ↝ (have_image planet13 spectrograph4)) ∷ (+ ↝ (have_image planet14 thermograph2)) ∷ (+ ↝ (have_image phenomenon15 infrared0)) ∷ (+ ↝ (have_image planet16 image3)) ∷ (+ ↝ (have_image star17 infrared0)) ∷ []

plan : Plan
plan = turn_to satellite4 star11 phenomenon9 ∷ turn_to satellite1 star4 groundstation3 ∷ turn_to satellite0 phenomenon9 star8 ∷ turn_to satellite2 star0 star4 ∷ switch_on instrument5 satellite2 ∷ calibrate satellite2 instrument5 star0 ∷ turn_to satellite2 star2 star0 ∷ turn_to satellite2 star5 star2 ∷ turn_to satellite2 planet6 star5 ∷ turn_to satellite2 phenomenon7 planet6 ∷ turn_to satellite2 star8 phenomenon7 ∷ turn_to satellite2 star10 star8 ∷ take_image satellite2 star10 instrument5 thermograph2 ∷ turn_to satellite2 planet13 star10 ∷ take_image satellite2 planet13 instrument5 spectrograph4 ∷ turn_to satellite2 planet14 planet13 ∷ take_image satellite2 planet14 instrument5 thermograph2 ∷ turn_to satellite3 star2 phenomenon9 ∷ switch_on instrument7 satellite3 ∷ calibrate satellite3 instrument7 star2 ∷ turn_to satellite3 star5 star2 ∷ take_image satellite3 star5 instrument7 image3 ∷ turn_to satellite3 star8 star5 ∷ take_image satellite3 star8 instrument7 image3 ∷ turn_to satellite3 planet16 star8 ∷ take_image satellite3 planet16 instrument7 image3 ∷ turn_to satellite4 phenomenon15 star11 ∷ turn_to satellite4 star17 phenomenon15 ∷ turn_to satellite4 star2 star17 ∷ switch_on instrument8 satellite4 ∷ calibrate satellite4 instrument8 star2 ∷ turn_to satellite4 planet6 star2 ∷ take_image satellite4 planet6 instrument8 infrared1 ∷ turn_to satellite4 star11 planet6 ∷ take_image satellite4 star11 instrument8 infrared1 ∷ turn_to satellite4 phenomenon15 star11 ∷ take_image satellite4 phenomenon15 instrument8 infrared0 ∷ turn_to satellite4 star11 phenomenon15 ∷ turn_to satellite4 star17 star11 ∷ take_image satellite4 star17 instrument8 infrared0 ∷ turn_to satellite4 star11 star17 ∷ turn_to satellite4 phenomenon7 star11 ∷ take_image satellite4 phenomenon7 instrument8 infrared1 ∷ turn_to satellite4 star11 phenomenon7 ∷ halt

Derivation : Γ ⊢ plan ∶ P ↝ Q 
Derivation = from-yes (solver Γ plan P Q)
